In [13]:
import pandas as pd

In [16]:
#!pip install tables

In [17]:
!ls /workspace/mnt/crucial_2TB/111_Extra_Data/Macys/

all_wearables20180810  archive1_1	   imgs224_1000
archive17	       archive1_1.tar.bz2  imgs260_3150
archive17.tar.bz2      archive28	   rayimages2_cleaned.h5
archive1_0	       archive28.tar.bz2   xtrain3150_260260.csv
archive1_0.tar.bz2     archive8		   xtrainonly1000.csv

In [18]:
path = '/workspace/mnt/crucial_2TB/111_Extra_Data/Macys/'

In [ ]:
imgattrs = pd.read_hdf(path + 'rayimages2_cleaned.h5')

In [35]:
len(imgattrs)

3434720

In [33]:
imgattrs.head(10)

,PRODUCT_ID,PRODUCT_COLORWAY_ID,COLORWAY_IMAGE_ROLE_TYPE,IMAGE_ID,PRODUCT_TYPE,SIZE_RANGE,GENDER
IMAGE_FILE,,,,,,,
2/8/2878730_3748135.jpg,2878730,2464687,CPRI,3748135,BEAUTY_TOOL,Regular,Unisex
2/8/2878730_3783475.jpg,2878730,2464687,CADD,3783475,BEAUTY_TOOL,Regular,Unisex
1/5/1506322_2880153.jpg,1506322,1416673,CPRI,2880153,APPAREL,Regular,Men
6/1/6199095_9859612.jpg,6199095,3362362,CPRI,9859612,PANTS,Regular,Boys
6/1/6199093_9859615.jpg,6199093,3362361,CPRI,9859615,PANTS,Regular,Boys
5/8/5809870_9905253.jpg,5809870,3379453,CPRI,9905253,PANTS,Regular,Boys
5/8/5809870_9905255.jpg,5809870,3379453,CADD,9905255,PANTS,Regular,Boys
6/6/6650710_2974956.jpg,6650710,3371951,CPRI,2974956,PANTS,Petites,Women
6/6/6650710_2703690.jpg,6650710,3371959,CPRI,2703690,PANTS,Petites,Women
6/6/6650710_8669828.jpg,6650710,3371971,CADD,8669828,PANTS,Petites,Women

In [34]:
imgattrs.tail(10)

,PRODUCT_ID,PRODUCT_COLORWAY_ID,COLORWAY_IMAGE_ROLE_TYPE,IMAGE_ID,PRODUCT_TYPE,SIZE_RANGE,GENDER
IMAGE_FILE,,,,,,,
4/4/447716_722005.jpg,447716,221800,CPRI,722005,BOAT_SHOE,Regular,Men
4/4/447714_722000.jpg,447714,221790,CPRI,722000,BOAT_SHOE,Regular,Men
6/6/660608_1128258.jpg,660608,517821,CPRI,1128258,BOAT_SHOE,Regular,Men
4/5/458316_738934.jpg,458316,235942,CPRI,738934,BOAT_SHOE,Regular,Men
4/5/458316_740442.jpg,458316,235943,CPRI,740442,BOAT_SHOE,Regular,Men
6/4/640473_1120274.jpg,640473,478606,CPRI,1120274,BOAT_SHOE,Big & Tall,Men
6/4/644593_1095724.jpg,644593,486320,CPRI,1095724,BOAT_SHOE,Regular,Men
5/4/543251_797225.jpg,543251,343535,CPRI,797225,BOAT_SHOE,Regular,Men
5/4/543251_797223.jpg,543251,343536,CPRI,797223,BOAT_SHOE,Regular,Men
5/4/543791_1143068.jpg,543791,344088,CPRI,1143068,BOAT_SHOE,Regular,Men

In [26]:
imgattrs.query('PRODUCT_TYPE == "BOAT_SHOE"')[:3]

,PRODUCT_ID,PRODUCT_COLORWAY_ID,COLORWAY_IMAGE_ROLE_TYPE,IMAGE_ID,PRODUCT_TYPE,SIZE_RANGE,GENDER
IMAGE_FILE,,,,,,,
5/1/5173835_8479539.jpg,5173835,2972242,CADD,8479539,BOAT_SHOE,Regular,Men
5/1/5173835_8479541.jpg,5173835,2972242,CADD,8479541,BOAT_SHOE,Regular,Men
4/6/4688833_8519958.jpg,4688833,2799739,CADD,8519958,BOAT_SHOE,Regular,Men

In [27]:
prod_types = set(imgattrs['PRODUCT_TYPE'])

In [28]:
len(prod_types)

138

In [29]:
[x for x in prod_types if 'shoe' in x.lower()]

['BOAT_SHOE', 'SHOE']

In [32]:
shoes = imgattrs.query('"SHOE" in PRODUCT_TYPE')
len(shoes)

384261

In [31]:
shoes.head()

,PRODUCT_ID,PRODUCT_COLORWAY_ID,COLORWAY_IMAGE_ROLE_TYPE,IMAGE_ID,PRODUCT_TYPE,SIZE_RANGE,GENDER
IMAGE_FILE,,,,,,,
5/8/5860413_9882517.jpg,5860413,3375538,CADD,9882517,SHOE,Regular,Women
5/8/5814376_9882308.jpg,5814376,3375523,CADD,9882308,SHOE,Regular,Women
5/8/5814376_9882313.jpg,5814376,3375524,CADD,9882313,SHOE,Regular,Women
6/5/6571113_9877407.jpg,6571113,3373756,CADD,9877407,SHOE,Regular,Women
6/5/6571113_9877409.jpg,6571113,3373756,CADD,9877409,SHOE,Regular,Women